const tbl_18 = {
    name: 'tbl_18_customer',
    keys: ['no'],
    fields: {
        address: 'Address',
        address_2: 'Address2',
        base_calendar_code: 'BaseCalendarCode',
        billto_customer_no: 'BilltoCustomerNo',
        blocked: 'Blocked',
        city: 'City',
        contact: 'Contact',
        contact_type: 'ContactType',
        currency_code: 'CurrencyCode',
        currency_id: 'CurrencyId',
        e_mail: 'EMail',
        fax_no: 'FaxNo',
        gen_bus_posting_group: 'GenBusPostingGroup',
        language_code: 'LanguageCode',
        location_code: 'LocationCode',
        mobile_phone_no: 'MobilePhoneNo',
        name: 'Name',
        name_2: 'Name2',
        no: 'No',
        payment_method_code: 'PaymentMethodCode',
        phone_no: 'PhoneNo',
        primary_contact_no: 'PrimaryContactNo',
        responsibility_center: 'ResponsibilityCenter',
        salesperson_code: 'SalespersonCode',
        search_name: 'SearchName',
        shipment_method_code: 'ShipmentMethodCode',
        shipto_code: 'ShiptoCode',
        system_id: 'SystemId',
        system_modified_at: 'SystemModifiedAt',
        telex_no: 'TelexNo',
    },
};

export default tbl_18;
