const tbl_99000772 = {
    name: 'tbl_99000772_production_bom_line',
    keys: ['production_bom_no', 'version_code', 'line_no'],
    fields: {
        production_bom_no: 'production_bom_no',
        version_code: 'version_code',
        line_no: 'line_no',
        type: 'type',
        no: 'no',
        description: 'description',
        unit_of_measure_code: 'unit_of_measure_code',
        quantity: 'quantity',
        position: 'position',
        position_2: 'position_2',
        position_3: 'position_3',
        lead_time_offset: 'lead_time_offset',
        routing_link_code: 'routing_link_code',
        scrap: 'scrap',
        variant_code: 'variant_code',
        comment: 'comment',
        starting_date: 'starting_date',
        ending_date: 'ending_date',
        length: 'length',
        width: 'width',
        weight: 'weight',
        depth: 'depth',
        calculation_formula: 'calculation_formula',
        quantity_per: 'quantity_per',
        lot_size: 'lot_size',
        min_consumption: 'min_consumption',
        notes: 'notes',
        system_id: 'system_id',
    },
};
export default tbl_99000772;
