const tbl_50151 = {
    name: 'tbl_50151_bsv_acc_change_control_request',
    keys: ['ccr_no', 'version'],
    fields: {
        ccr_no: 'CCRNo',
        version: 'Version',
        approval_status: 'ApprovalStatus',
        building: 'Building',
        centerline: 'Centerline',
        change_for_improvement: 'ChangeForImprovement',
        change_requirements_by_customer: 'ChangeRequirementsByCustomer',
        customer_code: 'CustomerCode',
        customer_name: 'CustomerName',
        desciption_of_change_requested: 'DesciptionOfChangeRequested',
        effect_to_mix_up: 'EffectToMixUp',
        effect_to_mix_up_answer: 'EffectToMixUpAnswer',
        effect_to_mix_up_pic: 'EffectToMixUpPIC',
        effect_to_safety_food: 'EffectToSafetyFood',
        effect_to_safety_food_pic: 'EffectToSafetyFoodPIC',
        effect_to_sop: 'EffectToSOP',
        effect_to_soppic: 'EffectToSOPPIC',
        machine: 'Machine',
        other: 'Other',
        other_details: 'OtherDetails',
        process: 'Process',
        product_structure: 'ProductStructure',
        raw_material: 'RawMaterial',
        reason_other: 'ReasonOther',
        reason_other_details: 'ReasonOtherDetails',
        safety_food_answer: 'SafetyFoodAnswer',
        sop_answer: 'SOPAnswer',
        system_modified_at: 'SystemModifiedAt',
        technical: 'Technical',
        test_method: 'TestMethod',
        total_approvals_details: 'TotalApprovalsDetails',
        total_collaborators_details: 'TotalCollaboratorsDetails',
        total_press_follow_actions: 'TotalPressFollowActions',
        total_relative_dept_details: 'TotalRelativeDeptDetails',
        total_relative_dept_issue_details: 'TotalRelativeDeptIssueDetails',
        total_released_prod_order: 'TotalReleasedProdOrder',
    },
};
export default tbl_50151;
