const tbl_5405 = {
    name: 'tbl_5405_production_order',
    keys: ['no', 'status'],
    fields: {
        status: 'Status',
        no: 'No',
        description: 'Description',
        search_description: 'SearchDescription',
        description_2: 'Description2',
        source_type: 'SourceType',
        source_no: 'SourceNo',
        variant_code: 'VariantCode',
        due_date: 'DueDate',
        blocked: 'Blocked',
        quantity: 'Quantity',
        no_series: 'NoSeries',
        planned_order_no: 'PlannedOrderNo',
        firm_planned_order_no: 'FirmPlannedOrderNo',
        assigned_user_id: 'AssignedUserID',
        manuacturing_type: 'ManuacturingType',
        system_modified_at: 'SystemModifiedAt',
        total_prod_order_components: 'TotalProdOrderComponents',
        total_prod_order_lines: 'TotalProdOrderLines',
        total_prod_order_routings: 'TotalProdOrderRoutings',
    },
};
export default tbl_5405;
