const tbl_50125 = {
    name: 'tbl_50125_bsv_acc_graphic_art_gravure',
    keys: ['gos', 'version'],
    fields: {
        '1_eyemarks_left_side': '1EyemarksLeftSide',
        '1_eyemarks_left_side_x': '1EyemarksLeftSideX',
        '1_eyemarks_left_side_y': '1EyemarksLeftSideY',
        '1_eyemarks_right_side': '1EyemarksRightSide',
        '1_eyemarks_right_side_x': '1EyemarksRightSideX',
        '1_eyemarks_right_side_y': '1EyemarksRightSideY',
        '2_eyemarks': '2Eyemarks',
        '2_eyemarks_x': '2EyemarksX',
        '2_eyemarks_y': '2EyemarksY',
        approve_cust_and_factory: 'ApproveCustAndFactory',
        bag_type: 'BagType',
        barcode: 'Barcode',
        barcode_color: 'BarcodeColor',
        barcode_no: 'BarcodeNo',
        color_quantity: 'ColorQuantity',
        color_target: 'ColorTarget',
        confirmation: 'Confirmation',
        content_matching: 'ContentMatching',
        cromalin_date: 'Cromalin date',
        cust_approve_standard_delta_e: 'CustApproveStandardDeltaE',
        customer_approve_the_color: 'Customer approve the color',
        customer_code: 'CustomerCode',
        customer_info_no: 'CustomerInfoNo',
        customer_name: 'CustomerName',
        customer_part_no: 'CustomerPartNo',
        cylinder_delivery_date: 'Cylinder delivery date',
        cylinder_order_date: 'Cylinder order date',
        date: 'Date',
        dimension_height: 'DimensionHeight',
        dimension_tolerence: 'DimensionTolerence',
        dimension_width: 'DimensionWidth',
        employee_id: 'EmployeeID',
        employee_name: 'EmployeeName',
        eyemark_bottom: 'EyemarkBottom',
        eyemark_color: 'EyemarkColor',
        eyemark_top: 'EyemarkTop',
        film_size: 'FilmSize',
        gos: 'GOS',
        graft_structure: 'GraftStructure',
        graphic: 'Graphic',
        graphic_design: 'GraphicDesign',
        graphic_ref: 'GraphicRef',
        in_color: 'InColor',
        ink_brightness: 'InkBrightness',
        item_name: 'ItemName',
        item_no: 'ItemNo',
        lamination_type: 'LaminationType',
        margin: 'Margin',
        note: 'Note',
        pdf_file_date: 'Pdf file date',
        press_wind: 'PressWind',
        print_direction_1: 'PrintDirection1',
        print_direction_2: 'PrintDirection2',
        print_direction_3: 'PrintDirection3',
        print_direction_4: 'PrintDirection4',
        print_direction_5: 'PrintDirection5',
        print_direction_6: 'PrintDirection6',
        print_direction_7: 'PrintDirection7',
        print_direction_8: 'PrintDirection8',
        print_direction_9: 'PrintDirection9',
        printed_sample: 'PrintedSample',
        printed_side: 'Printed side',
        roll_bag: 'RollBag',
        samp_print_and_customer_approve: 'SampPrintAndCustomerApprove',
        sample_approve: 'Sample approve',
        sample_description: 'SampleDescription',
        sample_printed_self_check: 'Sample printed & self-check',
        sample_type: 'Sample type',
        shaft_core: 'ShaftCore',
        shaft_length: 'ShaftLength',
        shaft_perimeter: 'ShaftPerimeter',
        spec_of_product: 'SpecOfProduct',
        status: 'Status',
        system_modified_at: 'SystemModifiedAt',
        // total_color_details: 'TotalColorDetails',
        // total_ink_consump_details: 'TotalInkConsumpDetails',
        // total_printers_details: 'TotalPrintersDetails',
        // total_remarks_details: 'TotalRemarksDetails',
        unit_h: 'UnitH',
        unit_w: 'UnitW',
        vendor_code: 'VendorCode',
        vendor_name: 'VendorName',
        version: 'Version',
    },
};
export default tbl_50125;
