const tbl_5406 = {
    name: 'tbl_5406_prod__order_line',
    keys: ['status', 'prod_order_no', 'line_no'],
    fields: {
        bin_code: 'BinCode',
        bsvacca_graphic_order_sheet: 'BSVACCAGraphicOrderSheet',
        bsvacca_order_line_no: 'BSVACCAOrderLineNo',
        bsvacca_order_no: 'BSVACCAOrderNo',
        bsvacca_spec_of_product: 'BSVACCASpecOfProduct',
        bsvaccaccr_no: 'BSVACCACCRNo',
        description: 'Description',
        description_2: 'Description2',
        due_date: 'DueDate',
        ending_date: 'EndingDate',
        ending_date_time: 'EndingDateTime',
        ending_time: 'EndingTime',
        finished_qty_base: 'FinishedQtyBase',
        finished_quantity: 'FinishedQuantity',
        item_no: 'ItemNo',
        line_no: 'LineNo',
        location_code: 'LocationCode',
        prod_order_no: 'ProdOrderNo',
        production_bom_no: 'ProductionBOMNo',
        quantity: 'Quantity',
        quantity_base: 'QuantityBase',
        remaining_qty_base: 'RemainingQtyBase',
        remaining_quantity: 'RemainingQuantity',
        reserved_qty_base: 'ReservedQtyBase',
        reserved_quantity: 'ReservedQuantity',
        routing_no: 'RoutingNo',
        scrap: 'Scrap%',
        starting_date: 'StartingDate',
        starting_date_time: 'StartingDateTime',
        starting_time: 'StartingTime',
        status: 'Status',
        unitof_measure_code: 'UnitofMeasureCode',
        lane: 'lane',
        width_of_film: 'width_of_film',
        thickness: 'thickness',
        density_kgm: 'density_kgm',
        linear_meter_quantity: 'linear_meter_quantity',
    },
};
export default tbl_5406;
