const tbl_5409 = {
    name: 'tbl_5409_prod__order_routing_line',
    fields: {
        bsvacca_fixed_scrap_quantity: 'BSVACCAFixedScrapQuantity',
        bsvacca_operation_group: 'BSVACCAOperationGroup',
        bsvacca_scrap_group: 'BSVACCAScrapGroup',
        bsvacca_speed: 'BSVACCASpeed',
        bsvacca_speed_uom_code: 'BSVACCASpeedUOMCode',
        concurrent_capacities: 'ConcurrentCapacities',
        description: 'Description',
        direct_unit_cost: 'DirectUnitCost',
        fixed_scrap_qty_accum: 'FixedScrapQtyAccum',
        fixed_scrap_quantity: 'FixedScrapQuantity',
        indirect_cost_perct: 'IndirectCostPerct',
        input_quantity: 'InputQuantity',
        lot_size: 'LotSize',
        move_time: 'MoveTime',
        move_time_unitof_meas_code: 'MoveTimeUnitofMeasCode',
        next_operation_no: 'NextOperationNo',
        no: 'No',
        operation_no: 'OperationNo',
        overhead_rate: 'OverheadRate',
        prod_order_no: 'ProdOrderNo',
        routing_link_code: 'RoutingLinkCode',
        routing_no: 'RoutingNo',
        routing_reference_no: 'RoutingReferenceNo',
        routing_status: 'RoutingStatus',
        run_time: 'RunTime',
        run_time_unitof_meas_code: 'RunTimeUnitofMeasCode',
        scrap_factor_accumulated: 'ScrapFactorAccumulated',
        scrap_factor_perct: 'ScrapFactorPerct.',
        sequence_no_actual: 'SequenceNoActual',
        setup_time: 'SetupTime',
        setup_time_unitof_meas_code: 'SetupTimeUnitof MeasCode',
        status: 'Status',
        type: 'Type',
        wait_time: 'WaitTime',
        wait_time_unitof_meas_code: 'WaitTimeUnitofMeasCode',
        work_center_group_code: 'WorkCenterGroupCode',
        work_center_no: 'WorkCenterNo',
    },
};
export default tbl_5409;
